### ISSUE TITLE
how run instagram-scraper from crontab

### ISSUE THREAD

**Issue by grafist02511** [arc298/instagram-scraper#437]
line in crontab 
45 8 * * * instagram-scraper 229017473 --location --latest  -m 5
does not work
how to correct write the schedule in crontab? thank you

**Comment by Hrxn** [comment]
https://corntab.com/

https://crontab.guru/

**Comment by grafist02511** [comment]
> https://corntab.com/
> 
> https://crontab.guru/

thank's, but i know how use * * * * in schedule
Problem is : application works correctly from console, but not work in crontab...

**Comment by itsdante** [comment]
> > https://corntab.com/
> > https://crontab.guru/
> 
> thank's, but i know how use * * * * in schedule
> Problem is : application works correctly from console, but not work in crontab...

I manage to do this by creating a custom script to run on django rest framework, and changing the required input to the input I receive from the parameters

**Comment by aslmx** [comment]
Maybe a bit late, but always when you have a behavior like

> Problem is : application works correctly from console, but not work in crontab...

It is usually because the script has access to some environment variables that the cronjob has not!

You could try to run export from console and run export from a shell script that is run by cronjob and then compare the results to see what might be the cause.

Its very generic and not related to instagramscraper only.. But maybe that helps... :)

**Comment by aslmx** [comment]
so. I had the same challenge today. I found another issue where this was described. It was indeed a PATH issue that i could fix by observing the **export** in a script
see https://github.com/rarcega/instagram-scraper/issues/180

run which instagram-scraper in a shell. This prints the path to the executable.
use this fullpath in your script that you run from cron. Works for me this way.
Or you can try to adjust the PATH in crontab.

**Comment by grafist02511** [comment]
find module in /.local/bin/
