### ISSUE TITLE
ERROR:  Unable to scrape user - <PUBLIC account>

### ISSUE THREAD

**Issue by samuelvontucher** [arc298/instagram-scraper#679]
I have used instagram scraper a lot and I am very thankful that this tool exsists.
For the first time today I had problems with scraping public users. 

I am using anaconda with python 3.6 and instagram scraper version 1.9 and 1.9.1. Both versions do not work for me. 
I have tried unistalling and installing instagram scraper and also creating new anaconde environments but it always gives me the same error: Unable to scrape user - <PUBLIC account>

![instagram-scraper_github_issue](https://user-images.githubusercontent.com/60099869/116982056-a2d16280-acc8-11eb-9301-62a0b774912a.jpg)

My next step would be to reinstall anaconda but I would rather not do that if there is another solution. 

Any suggestions or solutions to the error?

**Comment by BoquanErwinChen** [comment]
I have the same issue.

**Comment by GitXormik** [comment]
I solved this by just putting in my -u and -p. It's weird that it required it, but I guess it needs to access a routing path.

**Comment by sixem** [comment]
Over the past months, Instagram have been cracking down on scraping by banning IPs (even many residential proxies) and limiting unauthorized access that stops people from scraping public accounts without logging in. A solution to this is to provide your username and password like GitXormik suggested above, but excess scraping while logged in can still lead to an account ban, so be careful about that.

You're definitely not doing anything wrong, and I don't think there is a good solution to this at the moment. You can try to use an account to scrape, but try not to go overboard with scraping in order to stay safe from any potential bans.

**Comment by samuelvontucher** [comment]
Thank you both for your anwsers! 

Using -u and -p worked for me. I also opened instagram and used it in the browser normally as @sixem suggested. But i don't if that had an effect 😄

**Comment by samuelvontucher** [comment]
Short update: 

I created an extra account for scraping and got banned. So I would advise to not use an important account.

**Comment by restyler** [comment]
> Short update:
> 
> I created an extra account for scraping and got banned. So I would advise to not use an important account.

for public accounts I can recommend https://rapidapi.com/restyler/api/instagram40 API which rotates clean residential proxies under the hood. this will save you a lot of time.
